version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start.sh jupyter lab