version: '3'

services:
  python:
    image: python:3.10
    container_name: python
    volumes:
      - .:/python
    working_dir: /python
    command: bash -c "pip install -r requirements.txt && top -b"

  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_lab
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: .
        target: /app
