services:

  postgres:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin     
      ports:
        - "5050:80"
      depends_on:
        - postgres
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      env_file:
      - .env

  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: